### ISSUE TITLE
BTHPS3 Driver not deleted upon click trigger

### ISSUE THREAD

**Issue by Timoteee** [nefarius/Legacinator#12]
As the title suggests, the old bthps3 drivers are being detected but aren't being deleted. When the tile is clicked on, the ui fades to white but the tile is still there and the bthps3 drivers still exist in system32

**Comment by nefarius** [comment]
Click trigger? Title clicked? What? Kindly provide more details, mate, I don't get what you mean 😅

**Comment by nefarius** [comment]
Oh, got it now, you click the tile but it doesn't successfully removes the detected items, understood 👍

**Comment by RACE4EVER** [comment]
Same thing here
Maybe a little guide to manually uninstall this?
I've found and deleted all "bthps3" name containing files at \DriverStore, but BthPS3 installer still shows a message to uninstall driver.
Maybe some register edits?

**Comment by nefarius** [comment]
It would be beneficial if someone could contribute a proper fix to Legacinator instead of hacking together some guide nobody will read.

**Comment by Timoteee** [comment]
> Same thing here Maybe a little guide to manually uninstall this? I've found and deleted all "bthps3" name containing files at \DriverStore, but BthPS3 installer still shows a message to uninstall driver. Maybe some register edits?


I made a guide a while ago on the bthps3 repo 

https://github.com/ViGEm/BthPS3/discussions/56#discussioncomment-4326240

**Comment by Timoteee** [comment]
> It would be beneficial if someone could contribute a proper fix to Legacinator instead of hacking together some guide nobody will read.

As much as I appreciate your service to the community, Unfortunately, I am not proficient enough to make code contributions. I have therefore contributed in whatever other way I could have as evident in [#56 in the BthPS3 repo](https://github.com/ViGEm/BthPS3/discussions/56#discussioncomment-4326240)  At the end of the day its your code, your program. Not everyone who uses GitHub or even report issues are coders or code enough to contribute forks.

**Comment by nefarius** [comment]
I deleted that release since it is buggy and only leads to confusion, need to harden and test old BthPS3 removal and also check the installed version or users might accidentally nuke a perfectly good installation from their system.

**Comment by nefarius** [comment]
This is no longer relevant since the BthPS3 setup has been completely overhauled to cleanly rip out all driver residue, if used.
