### ISSUE TITLE
Why did you make your software look like malware?

### ISSUE THREAD

**Issue by collincusce** [nefarius/Legacinator#26]
Bruuuuhhh you scared the shit out of me.

**Comment by nefarius** [comment]
To be fair, I have seen far uglier malware so that criticism hits hard, mate.

**Comment by chaser5419** [comment]
Kinda scared me too lol, but to be honest it's a great tool. Thanks for the update (｡･∀･)ﾉﾞ

**Comment by nefarius** [comment]
On a totally different note, maybe should hire a designer for future projects...

**Comment by collincusce** [comment]
Nahhh just keep it simple and you CANNOT go wrong. I think it's great you did something original, though!

**Comment by collincusce** [comment]
No more bombs in your installer, at least. Felt like I snagged something from Kazaa from back in the day. HAHAHA

**Comment by nefarius** [comment]
> No more bombs in your installer, at least. Felt like I snagged something from Kazaa from back in the day. HAHAHA

Yeah the icon pack was rather limited, but it's using all creative commons licensed stuff, always have to be careful with art and copyright and stuff. I should probably change it to something more common.

**Comment by collincusce** [comment]
ROCKETS!!!

**Comment by collincusce** [comment]
Feedback received, I think it's on the brain and that's enough for me. Thank you for listening.

**Comment by tjma2001** [comment]
> Bruuuuhhh you scared the shit out of me.

Nothing says you have been pwned quite like a surprise pink pony hovering in the middle of your screen, just long enough before you can grab a screenshot.

**Comment by nefarius** [comment]
> > Bruuuuhhh you scared the shit out of me.
> 
> Nothing says you have been pwned quite like a surprise pink pony hovering in the middle of your screen, just long enough before you can grab a screenshot.

I have I PhD in subtle marketing.

**Comment by DylRicho** [comment]
Just a question; now that Legacinator has uninstalled the ViGEM driver, which driver am I supposed to use for DS4Windows moving forward, since step 1 from the popup that appears when running it is to install the ViGEM driver.

**Comment by nefarius** [comment]
Legacinator doesn't uninstall ViGEmBus, no idea where you got that nonsense from.

**Comment by DylRicho** [comment]
> Legacinator doesn't uninstall ViGEmBus, no idea where you got that nonsense from.

There is no need to be rude, I was asking because that appears to be exactly what happened since DS4Windows always prompts me to install it when I open it up.

When I opened up Legacinator and there were three boxes. I clicked all three and they disappeared one by one. Now the driver is uninstalled.

**Comment by nefarius** [comment]
> There is no need to be rude, I was asking because that appears to be exactly what happened since DS4Windows always prompts me to install it when I open it up.

What is it with people being so brittle to feel offended by mere facts...

> I opened up Legacinator and there were three tiles. I clicked all three and they disappeared one by one. Now the driver is uninstalled. As it appears to detect "outdated components," I'm wondering if there was an updated version that I should instead use? Perhaps that is why it uninstalled it.

Which tiles exactly? Mind sharing the log? Otherwise just reinstall the latest ViGEmBus, as simple as that. Same location, my GitHub, since forever.

**Comment by DylRicho** [comment]
> What is it with people being so brittle to feel offended by mere facts...
You can word your sentences in a way that doesn't seem so argumentative. I am not "offended" that you stated your program doesn't delete drivers. I trust that you know what your software does and was merely trying to understand what had happened because that wasn't expected behavior for either of us. You simply could have conveyed that in a manner that wasn't condescending.
 
> Which tiles exactly? Mind sharing the log? Otherwise just reinstall the latest ViGEmBus, as simple as that. Same location, my GitHub, since forever.
I've just reinstalled the driver via DS4Windows and the tile shown is "Outdated ViGEmBus (Gen1) Driver found (v1.17.333.0)."

Clicking this tile removes it and then makes the popup to reinstall it in DS4Windows appear again.

If there is some kind of log associated with Legacinator, please help me locate it.

**Comment by nefarius** [comment]
Install [the latest version](https://github.com/nefarius/ViGEmBus/releases/tag/v1.21.442.0) and you're good to go, as simple as that. 

Legacinator does only what you tell it to do *except* when in updater mode, then the only thing it changes is the updater agent config, **nothing else**. So if you had an older ViGEmBus version, you probably got the warning and nuked it without reinstalling it, can't think of anything else that would match your situation.

The Log is in the same folder as the executable named `Legacinator.log`

**Comment by nefarius** [comment]
> I've just reinstalled the driver via DS4Windows and the tile shown is "Outdated ViGEmBus (Gen1) Driver found (v1.17.333.0)."

That means DS4Windows delivers/links to an outdated version, hence Legacinator picking it up as outdated.

**Comment by DylRicho** [comment]
> That means DS4Windows delivers/links to an outdated version, hence Legacinator picking it up as outdated.

That makes sense. For some reason I thought that both programs were associated with yourself, but I see now that this is incorrect.

Okay, so I've grabbed the driver from your repo. Legacinator picked up on an outdated updater which I assume is also from the DS4Windows linked driver, so I've gotten rid of that and everything is now good.

Thank you Ben for your help. Apologies for our misunderstanding earlier. :)

**Comment by nefarius** [comment]
> Thank you Ben for your help. Apologies for our misunderstanding earlier. :)

No worries, it's just the way I talk, no harm meant 🙏

**Comment by nefarius** [comment]
> Okay, so I've grabbed the driver from your repo. Legacinator picked up on an outdated updater which I assume is also from the DS4Windows linked driver, so I've gotten rid of that and everything is now good.

This situation will be streamlined some time later when I can publish a new setup, but one step at a time, the pile is still sky high.

**Comment by Mpissoni24** [comment]
ahahahha broooo i hate u!

**Comment by nefarius** [comment]
> ahahahha broooo i hate u!

What a most insightful and valuable comment, much appreciated!
