### ISSUE TITLE
no builds inside 1.0.25 folder on buildbot

### ISSUE THREAD

**Issue by orcutt989** [nefarius/Legacinator#4]
Thanks for updating the latest build link, however it looks like there arent any builds in your folder.

https://buildbot.vigem.org/builds/Legacinator/master/1.0.25/

![image](https://user-images.githubusercontent.com/5608027/184923243-9a0c66b2-1c3d-4644-881e-29765fc4a824.png)

**Comment by nefarius** [comment]
True, let me check that 🤔

**Comment by nefarius** [comment]
Ah I see why, because the build for that version already expired, triggering a new one.

**Comment by nefarius** [comment]
[Here we go](https://buildbot.vigem.org/builds/Legacinator/master/1.0.26/bin/Release/).

**Comment by orcutt989** [comment]
Very cool. Buildabot doesn't have a URL like https://buildbot.../latest that you could link to in the readme?

**Comment by nefarius** [comment]
Nope, the concept of "latest" doesn't exist on CI. Only build numbers which correspond to the build output version numbers. Why would you need a link like that? It's not recommended to share that anyway, only advanced users should tinker with the build artifacts, everyone else is supposed to use the GitHub releases, which do in fact offer a "latest" URL.

**Comment by orcutt989** [comment]
> Nope, the concept of "latest" doesn't exist on CI. Only build numbers which correspond to the build output version numbers.

I understand what you are saying but this is not necesarilly true. If you were publishing with GitHub actions and releasing, there are URLs that correspond to different artifact paths.  There is a URL that is quite popular that people use to pull the "latest" build, this can be "pre releases" or regular releases. https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases 

> Why would you need a link like that? It's not recommended to share that anyway, only advanced users should tinker with the build artifacts, everyone else is supposed to use the GitHub releases, which do in fact offer a "latest" URL.

Its not that I personally need it, but your Readme insinuates that you are linking to the latest "beta" or "pre release" "experimental" release.  It seems with buildbot you either have to link to the base folder or manually update to the latest artifact path which is not ideal from a functional perspective. Not a big deal, but just trying to provide some helpful feedback from the context of your Readme.

**Comment by nefarius** [comment]
I removed it as it seems to be only confusing, GitHub releases are the relevant ones anyway 😉

**Comment by nefarius** [comment]
> I understand what you are saying but this is not necesarilly true.

It is on my particular setup 😉
